### ISSUE TITLE
z-index Problem with navigation menu

### ISSUE THREAD

**Issue by beaubbe** [symphonycms/symphony-2#2406]
there is an overlapping of the submenu when navigation menu is on 2 lines
![image](https://cloud.githubusercontent.com/assets/2184547/7206785/e929a90c-e502-11e4-92e0-dda8b969c2b3.png)

**Comment by brendo** [comment]
I believe this is a dupe of #2402? Correct?

**Comment by beaubbe** [comment]
I don't think it's entirely the same. #2402 was for a z-index problem between the content and structure menu, which was fixed. This issue is for a z-index problem only within the content menu.

**Comment by brendo** [comment]
I believe this is the better fix which resolves this issue and #2402.

**Comment by nitriques** [comment]
Nope @brendo, the issue is still present. 85e8993 does not solve the issue... Removing the z-index does.

**Comment by nitriques** [comment]
The active li must have a higher z-index than the one whos not.

**Comment by brendo** [comment]
> The active li must have a higher z-index than the one whos not.

But it is? [Normal z-index](https://github.com/symphonycms/symphony-2/blob/85e89930d52b173e6a6d051e852e0cfe89aff029/symphony/assets/css/src/admin.css#L107) is `11000`. [Active z-index](https://github.com/symphonycms/symphony-2/blob/85e89930d52b173e6a6d051e852e0cfe89aff029/symphony/assets/css/src/admin.css#L124) is `12000`. Please refresh your cache, I'm not able to reproduce the error in Chrome 42 with this fix applied.

**Comment by nitriques** [comment]
We will test then...

**Comment by nitriques** [comment]
FIXED ! Thanks @brendo We must have tested it wrong.
