### ISSUE TITLE
"Files not writable ..." error whereas the directory was also the issue

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2439]
When saving Symphony's `preferences`, I encountered error messages on non writable JIT's `recipes` and `trusted-sites` files, but after made them writable there was still this error, because JIT's directory itself was not writable.

This also happens for e.g. `config.php` resp. its `manifest` folder, **but** in this case there is just a silent fail of saving.

Maybe there could be a check on directory too if it's writable and with a corresponding message if not? Or is this just a too obvious thing to do in non writable file cases?

Symphony 2.6.2

Thanks.

**Comment by nitriques** [comment]
Yup we should check this...

**Comment by brendo** [comment]
Looks like this problem more of a bug in JIT to actually do [some additional checks](https://github.com/symphonycms/jit_image_manipulation/blob/master/extension.driver.php#L364-L367) on the folder rather than the core.

The [General::writeFile](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.general.php#L920) method already does a folder check and returns `false` if it doesn't pass.

**Comment by nitriques** [comment]
@brendo but JIT already uses `General::writeFile` ... and we must prevent "just a silent fail of saving."... right ?

**Comment by jurajkapsz** [comment]
Yes, initially I wanted to log it into JIT, but I then confused myself with the fact, that it happens on the system save prefs level and at the same time I noticed the silent fail.

So there are two moments here:

1. JIT telling again about the files not writable though they are writable (when its folder is not writable)
2. Config itself fails to save giving no feedback (if manifest folder is not writable)

Maybe these should be logged as two separate issues. Let me know if I should do something about it.

Thanks.

**Comment by nitriques** [comment]
I will ensure to fix point 2) here, but yeah, if you could create another issue in the jit repo for point 1) it would be nice.

I have something ready for this, I just need some time to test it more.

**Comment by jurajkapsz** [comment]
> create another issue in the jit repo for point 1) it would be nice.

Ok, done: https://github.com/symphonycms/jit_image_manipulation/issues/107

**Comment by nitriques** [comment]
Thanks!

**Comment by jurajkapsz** [comment]
Thank you!

**Comment by brendo** [comment]
Is #2447 related to this (and therefore fixed by association?)

**Comment by DavidOliver** [comment]
I wouldn't have thought so. @nitriques?

**Comment by nitriques** [comment]
No it does not. I did not find the time to properly test and debug it, but we still have issues with this.

**Comment by brendo** [comment]
Is there an exact set of steps to recreate the issue? Particularly point 2? I'm getting error pages (nice ones) and messages at the moment, so I don't think my setup is triggering the same sort of errors

**Comment by jurajkapsz** [comment]
> Is there an exact set of steps to recreate the issue? Particularly point 2?

If the `manifest` folder has only `read` permissions, then nothing gets written down, but a `success` message is displayed upon saving.

**Comment by brendo** [comment]
I've added a `General::checkFile` method that the Preferences page is now using. This checks both the folder and file are read/write and if they are not, the usual permissions banner is shown.

**Comment by nitriques** [comment]
Nice!
