### ISSUE TITLE
Calendar wont open in 2.6.3/.4 with lang_german

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2521]
In Symphony `2.6.3` and `2.6.4` I have a section containing two `date fields`. `Show calendar` is activated with both. When system language is set to `german` with the recent `lang_german` extension the calendar date picker wont open.

![bildschirmfoto 2015-11-30 um 08 31 31](https://cloud.githubusercontent.com/assets/446874/11465954/cce547fe-973d-11e5-9ba3-7a0c8ecfdf76.png)

**Comment by animaux** [comment]
Is it possible the date-field calender fails to grab the localised date in `value=`?

Here’s the backend html in english:
/Users/goldwiege/Desktop/Bildschirmfoto 2015-11-30 um 08.40.13.png

And here in german:
/Users/goldwiege/Desktop/Bildschirmfoto 2015-11-30 um 08.40.37.png

**Comment by animaux** [comment]
Is it possible the date-field calender fails to grab the localised date in `<input … value= …`?

Here’s the backend html in english:

![bildschirmfoto 2015-11-30 um 08 40 13](https://cloud.githubusercontent.com/assets/446874/11466049/837cf372-973e-11e5-9244-ce1abda3b5a0.png)

And here in german:

![bildschirmfoto 2015-11-30 um 08 40 37](https://cloud.githubusercontent.com/assets/446874/11466040/7c189ab4-973e-11e5-9b4a-293f8dbf4b43.png)

**Comment by nitriques** [comment]
Ping @nilshoerrmann would you now what triggered this ?

**Comment by nilshoerrmann** [comment]
My guess are missing date settings in the config.

**Comment by nitriques** [comment]
Thanks Nils. @animaux BTW, which calendar are you talking about ? The one in the filter panel ?

**Comment by animaux** [comment]
@nilshoerrmann this is on a fresh installation of 2.6.3 updated to 2.6.4 shouldn’t the date settings be there in the config then? I’ve got:

		###### REGION ######
		'region' => array(
			'time_format' => 'H:i',
			'date_format' => 'd. F Y',
			'datetime_separator' => ', ',
			'timezone' => 'Europe/Berlin',
		),
		########

and

		###### LANG-GERMAN-STORAGE ######
		'lang-german-storage' => array(
			'date_format' => 'd.m.Y',
			'time_format' => 'H:i',
			'datetime_separator' => ' ',
		),
		########

@nitriques I’m referring to the calendar in the date field. The one in the filter works fine with german locale.

**Comment by nilshoerrmann** [comment]
> … shouldn’t the date settings be there in the config then?

The German localisation changes the core date settings from English to German formats. I remember having the problem that this leaded to missing date settings under certain circumstances I never investigated. Because the `data-format` attribute was missing in your example markup, this was my first guess. But I actually have no idea why it doesn't work.

The interesting part is that the `data` attributes are missing after enabling the German translation. So you should investigate that area. [Maybe the settings are translated for some reason?](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/fields/field.date.php#L483)

**Comment by nitriques** [comment]
So I have the feeling like it's not a core problem.... ?

**Comment by nilshoerrmann** [comment]
If field settings were translated, it would be a core issue. The German localisation only provides the German strings and changes the date formats. So there are 3 potential issues:

- damaged date and time settings (caused by the extension)
- strings that shouldn't be translated, are translated (core issue)
- strings that should be translated, are not translated (core issue)

Looking at Alex' preferences, the date and time settings are fine.

**Comment by nitriques** [comment]
As far as the core goes, Widget::Calendar relies on DateTimeObj (https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.widget.php#L869). DateTimeObj only calls __() for errors.

Does the extension overrides values in $date_mappings or $time_mapping properties of DateTimeObj  ?

**Comment by brendo** [comment]
Also, what is the last known good version of Symphony where this functionality worked?

**Comment by animaux** [comment]
Thanks guys. No message in console.

The problem must be somewhere else. I have an installation of `Symphony 2.6.3` with `Language German 2.2.0` that works fine. Weird. Maybe some other extension interfering. Will try the old extension-deactivation-game …

**Comment by animaux** [comment]
Ok, solved. I have switched the setting from

    ###### REGION ######
    'date_format' => 'd. F Y',

to 

    'date_format' => 'j. F Y',

and

    ###### LANG-GERMAN-STORAGE ######
    'date_format' => 'd.m.Y',

to

    'date_format' => 'd F Y',

Resulting in a working calendar popup. I remember there was some talk about the calendar date formats some time ago. The result was a console message listing the possible working formats. However, from a user perspective I shouldn’t be able to pick a date format in the installer that breaks something somewhere else, should I? Though this is only a problem with the `german_lang` extension.

**Comment by nilshoerrmann** [comment]
> However, from a user perspective I shouldn’t be able to pick a date format in the installer that breaks something somewhere else, should I?

The installer and the calendar make use of the same set of predefined formats:
https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/core/class.datetimeobj.php#L29-L44

If that's not true, that's the actual bug you are hunting.

**Comment by animaux** [comment]
Hmm. My uneducated guess is the calendar chokes on the interpretation of a literal date translated to german.

**Comment by nilshoerrmann** [comment]
Could you please elaborate?

**Comment by animaux** [comment]
Obviously the Calendar can interpretate the `<input value="25.11.2016 12.00">` (in case it actually looks there). But probably chokes on the translated `<input value="25. November 2016, 12.00">` because it’s the right format but german?

Hmn, thinking of it that only makes half sense since `November` should be the same in german and english. I’m lost here …

**Comment by nilshoerrmann** [comment]
I don't know if this changed in the meantime, but Symphony originally bundled Moment.js with locals.
The important question is: Why are `data-calendar` and `data-format` missing in combination with certain format settings.

Symphony needs to know the values of `data-format` in order to parse dates for the calendar widget.

I've not used the calendar for quite a while so I'm not really into it anymore, but you need to track down the reasons for the different markup output. That said, I don't think this issue is solved, you just worked around it.

**Comment by animaux** [comment]
> That said, I don't think this issue is solved, you just worked around it.

Good point!

**Comment by nitriques** [comment]
> The important question is: Why are data-calendar and data-format missing in combination with certain format settings.

Because it does not find the format: https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.widget.php#L869

Question: @animaux Does the calendar works if you get rid of the `if ($date) {` statement ?

**Comment by animaux** [comment]
@nitriques getting rid of the statement you mentioned makes the calendar open. But it displays the current date and not the date actually set in the field. Looks like it defaults since it cannot find or read the actual date.

**Comment by nilshoerrmann** [comment]
There are two things you should do:

1. Make sure that [this statement is logged in the console](https://github.com/symphonycms/symphony-2/issues/2306#issuecomment-69198634) using your initial date format (`d. F Y`).  
If it's not, that's a bug.
2. Add the formats `'d. F Y' => 'DD. MMMM YYYY'` and `'d. M Y' => 'DD. MMM. YYYY'` [to the date mapping](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/core/class.datetimeobj.php#L29-L44).

**Comment by animaux** [comment]
1. No statement when using the initial date format.

2. Adding the two formats fixes the issue!

**Comment by nilshoerrmann** [comment]
1. So this is the actual bug that needs to be fixed.
2. Great! Just bundle that in a pull request.

**Comment by animaux** [comment]
I’m not allowed to send a pull request :’(

**Comment by nilshoerrmann** [comment]
How's that possible?

**Comment by animaux** [comment]
Maybe I’m doing it wrong … or *likely*.

**Comment by animaux** [comment]
Ah yes, I think I remember to do it properly :)

**Comment by animaux** [comment]
https://github.com/symphonycms/symphony-2/pull/2525

**Comment by nitriques** [comment]
Thanks @animaux !

**Comment by nitriques** [comment]
Fixed in #2525

**Comment by animaux** [comment]
As @nilshoerrmann mentioned the bug remains: no warning is issued in the console if the format used is incompatible with the calendar.

**Comment by nitriques** [comment]
> no warning is issued in the console if the format used is incompatible with the calendar.

That's true.. Should we add it ? I just do not know how: since the data attribute is not there, the plugin won't run at all.

**Comment by animaux** [comment]
@nilshoerrmann should know when or how this should be triggered. I’ve no idea.

**Comment by brendo** [comment]
It *should* be triggered when the [`data-format` attribute is `undefined`](https://github.com/symphonycms/symphony-2/blob/master/symphony/assets/js/src/symphony.calendar.js#L19-L26). Let me take a quick look and see if I can reproduce this, it may be that this attribute is actually returning a value.

**Comment by brendo** [comment]
Interestingly, I can't reproduce this by setting my date format to `d. F Y` on `2.6.x` with that format commented out, the console is populated as shown in the screenshot below:

![Chrome](https://cloud.githubusercontent.com/assets/69268/11680203/39bef922-9ea2-11e5-8286-390903ea42fc.png)

![Firefox](https://cloud.githubusercontent.com/assets/69268/11680252/921e4adc-9ea2-11e5-87fe-da1ec6490f8f.png)

It's not actually a warning, rather it's `console.info`. Which browser are you using @animaux?

**Comment by animaux** [comment]
@brendo You need to have lang_german installed and system language set to german. I’ve tested on Safari 9.

**Comment by brendo** [comment]
Done, still cannot reproduce, I've copied the values as [described here](https://github.com/symphonycms/symphony-2/issues/2521#issuecomment-160881347):

![screen shot 2015-12-09 at 6 36 48 pm](https://cloud.githubusercontent.com/assets/69268/11680375/84d9023a-9ea3-11e5-8ec8-e0b7db476b31.png)
![screen shot 2015-12-09 at 6 36 07 pm](https://cloud.githubusercontent.com/assets/69268/11680376/85042104-9ea3-11e5-8a21-b91325891867.png)

**Comment by animaux** [comment]
@brendo do you have the https://github.com/symphonycms/symphony-2/pull/2525 already running?

**Comment by brendo** [comment]
Not really, I'm using `2.6.x` as the base, but I have commented out the two formats added in #2525.

Is it just Safari that doesn't have the message? Might the Console be on the 'Errors' tab instead of 'All'?

**Comment by animaux** [comment]
D’oh! You’re right @brendo it’s no error and I had my console set to only show errors. This resets with every bloody Safari update, grrrrr! 

Many thanks, I’m closing this! :D

**Comment by brendo** [comment]
Woohoo, I'm glad it was something simple in the end :dancer:

**Comment by animaux** [comment]
And I’m ashamed it wasn’t a bug in the end :{

**Comment by brendo** [comment]
Don't be ashamed, always good to double check!

**Comment by animaux** [comment]
Cheers! I’ll blame Safari’s ever changing web inspector then :)

**Comment by nitriques** [comment]
@brendo Do we need to revert 8cbec80 then ?

**Comment by brendo** [comment]
No, it's good :)

**Comment by nitriques** [comment]
Great, thanks!
